motor_info:
  min_pwm: 0.50  # 1000 ~ dshot 0
  max_pwm: 0.95  # 0.95 ~ dshot 1800
  min_thrust: 0.0  # [N]
  force_landing_thrust: 2.5  # [N]

  # use f_norm instead of fz in case the test bed is tilted. Use 25.20V data for fitting.
  krpm_square_to_thrust_ratio: 0.0205  # N/(kRPM)^2
  krpm_square_to_thrust_bias: -0.1284  # N
  m_f_rate: -0.0112

  pwm_conversion_mode: 1  # POLYNOMIAL Mode
  # Note that for SQRT mode, only poly2 is 10x, others are 1x, and the relationship is fz = f(pwm).
  # But for POLYNOMIAL mode, the coefficients are 10x one by one, and the relationship is pwm = f(fz).
  # Specifically, get the coefficients from aerial_robot_nerve/motor_test/scripts/analyze_data.py, the second group.
  # SQRT Mode ref: https://github.com/jsk-ros-pkg/jsk_aerial_robot/blob/master/aerial_robot_nerve/spinal/mcu_project/lib/Jsk_Lib/flight_control/attitude/attitude_control.cpp#L825
  # POLYNOMIAL Mode ref: https://github.com/jsk-ros-pkg/jsk_aerial_robot/blob/master/aerial_robot_nerve/spinal/mcu_project/lib/Jsk_Lib/flight_control/attitude/attitude_control.cpp#L832
  vel_ref_num: 4
  ref1:
    voltage: 24.51  # [V]
    max_thrust: 14.8288  # [N]
    polynominal3: 14.07183960  # x10^3
    polynominal2: -35.17458882  # x10^2
    polynominal1: 50.52221718  # x10^1
    polynominal0: 51.90997902  # x10^0
  ref2:
    voltage: 23.57  # [V]
    max_thrust: 14.2608  # [N]
    polynominal3: 14.45337979  # x10^3
    polynominal2: -36.01032878  # x10^2
    polynominal1: 52.22583338  # x10^1
    polynominal0: 52.01055881  # x10^0
  ref3:
    voltage: 22.58  # [V]
    max_thrust: 13.5394  # [N]
    polynominal3: 17.25312430  # x10^3
    polynominal2: -41.22172739  # x10^2
    polynominal1: 56.20296435  # x10^1
    polynominal0: 52.00782895  # x10^0
  ref4:
    voltage: 21.60  # [V]
    max_thrust: 12.9125  # [N]
    polynominal3: 19.01859718  # x10^3
    polynominal2: -44.83082360  # x10^2
    polynominal1: 59.82466580  # x10^1
    polynominal0: 51.97353895  # x10^0
